- name: Get latest stable kubectl version
  shell: curl -L -s https://dl.k8s.io/release/stable.txt
  register: kubectl_version
  changed_when: false

- name: Download kubectl binary
  get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
    
- name: Download minikube
  get_url:
    url: https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
    dest: /usr/local/bin/minikube 
    mode: '0755'

- name: Rename minikube binary
  command: mv /usr/local/bin/minikube-linux-amd64 /usr/local/bin/minikube
  args:
    creates: /usr/local/bin/minikube

- name: Ensure minikube is executable
  file:
    path: /usr/local/bin/minikube
    mode: '0755'
    state: file

- name: Start Minikube
  become: false
  shell: minikube start
  args:
    executable: /bin/bash

- name: Download get-helm-3 script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Run get-helm-3 script
  command: /tmp/get_helm.sh
